import PublicNav from "../components/PublicNav.jsx";

// Terms of Service for Reliafy Cloud. Plain-language on purpose; reuses the
// blog typography. The self-hosted open-source version is governed by the
// AGPL-3.0 license, not these terms.
export default function TermsPage() {
  return (
    <div className="landing">
      <PublicNav />
      <article className="blog-article">
        <header className="blog-article-head">
          <div className="blog-card-meta"><time>Effective 7 August 2026</time></div>
          <h1>Terms of Service</h1>
        </header>
        <div className="blog-prose">
          <p>
            These terms govern your use of <strong>Reliafy Cloud</strong>, the hosted
            version of Reliafy ("the Service"). The self-hosted open-source version is
            licensed separately under the AGPL-3.0 and is not covered by these terms.
            By creating an account or using the Service you agree to them.
          </p>

          <h2>Your account</h2>
          <p>
            You need an account to use the Service. Keep your credentials secure —
            you're responsible for activity under your account. You must provide a
            working email address, and you must be legally able to enter into this
            agreement.
          </p>

          <h2>Your data</h2>
          <p>
            The datasets, models, and diagrams you create belong to you. We store and
            process them only to operate the Service and never sell them or use them
            to train machine-learning models. You can delete your data at any time
            from within the app, and you can request full account deletion by email.
          </p>

          <h2>Plans, credits, and billing</h2>
          <p>
            The free plan has limits on saved items. The Pro subscription renews
            monthly until cancelled and includes a monthly allowance of AI credits;
            you can cancel any time from the billing portal and keep access until the
            end of the paid period. Prepaid AI credit packs are one-time purchases;
            credits don't expire. AI usage draws down your credit balance based on
            the compute consumed. Payments are processed by Stripe — we never see or
            store your card details. Unless required by law, payments are
            non-refundable, but if something went wrong, email us and we'll be
            reasonable.
          </p>

          <h2>The AI assistant</h2>
          <p>
            The assistant produces statistical output generated by a large language
            model. It can make mistakes. Its output is <strong>not</strong> engineering
            advice: you are responsible for reviewing any model, diagram, or
            recommendation before using it in decisions that affect safety,
            operations, or money. For critical applications, have qualified engineers
            verify the results.
          </p>

          <h2>Engineering decisions and outcomes</h2>
          <p>
            Reliafy is a modelling and calculation tool. Everything it produces —
            fitted distributions, reliability and availability figures, replacement
            intervals, forecasts, RCM assessments — depends entirely on the data and
            assumptions you supply, and every model is a simplification of a real
            system. Judging whether a result is fit for your purpose is your
            responsibility, not ours.
          </p>
          <p>
            You are solely responsible for any decision you take on the basis of the
            Service and for the outcomes of that decision — including maintenance,
            inspection, replacement, spares, design, procurement, compliance, and
            safety decisions. To the maximum extent permitted by law, we are not
            liable for those decisions or their consequences, whether the output came
            from the statistical engine or the AI assistant. Where a decision could
            affect safety, the environment, regulatory compliance, or significant
            cost, have it reviewed by a qualified engineer who has checked the inputs
            and the assumptions behind it.
          </p>
          <p>
            Nothing in this section excludes rights that cannot be excluded under
            applicable law — see <em>Liability</em> below.
          </p>

          <h2>Acceptable use</h2>
          <p>
            Don't attempt to break, overload, or gain unauthorised access to the
            Service or other users' data; don't use it for unlawful purposes; and
            don't resell access to it. We may suspend accounts that put the Service
            or other users at risk.
          </p>

          <h2>Availability and changes</h2>
          <p>
            We aim to keep the Service reliable but provide it "as is", without
            warranties of uninterrupted availability. We may change features over
            time. If we ever discontinue the Service, we'll give reasonable notice so
            you can export your data — and because the core is open source, you can
            always keep working self-hosted.
          </p>

          <h2>Liability</h2>
          <p>
            To the maximum extent permitted by law, our total liability arising from
            the Service is limited to the amount you paid us in the twelve months
            before the claim. Nothing in these terms excludes rights that cannot be
            excluded under applicable consumer law, including the Australian Consumer
            Law.
          </p>

          <h2>Changes to these terms</h2>
          <p>
            If we make material changes we'll note it on this page and, for
            significant changes, notify you by email. Continued use after a change
            means you accept the updated terms.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these terms: <a href="mailto:hello@reliafy.com">hello@reliafy.com</a>.
            These terms are governed by the laws of Australia.
          </p>
        </div>
      </article>
      <footer className="landing-foot"><span>© Reliafy</span></footer>
    </div>
  );
}
